name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pull_request_${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  build:
    name: Build
    uses: containifyci/engine-ci/.github/workflows/engine-ci-workflow.yml@v0
    secrets: inherit
    with:
      install_binary: true
      dockerhub_user: "containifyci"

